TOP_LEFT_CORNER = (0, 0)

FIRST_BACKGROUND_ID = "1b"
SECOND_BACKGROUND_ID = "2b"
THIRD_BACKGROUND_ID = "3b"
FOURTH_BACKGROUND_ID = "4b"

FIRST_BACKGROUND_PATH = "assets/background_grass.png"
SECOND_BACKGROUND_PATH = ""
THIRD_BACKGROUND_PATH = ""
FOURTH_BACKGROUND_PATH = ""

BACKGROUND_PATHS = {
    FIRST_BACKGROUND_ID: FIRST_BACKGROUND_PATH,
    SECOND_BACKGROUND_ID: SECOND_BACKGROUND_PATH,
    THIRD_BACKGROUND_ID: THIRD_BACKGROUND_PATH,
    FOURTH_BACKGROUND_ID: FOURTH_BACKGROUND_PATH,
}

PROJECTILE_FRAME_SPACE = 0
PROJECTILE_FRAME_COUNT = 0
PROJECTILE_WIDTH = 0
PROJECTILE_HEIGHT = 0

FIRST_PROJECTILE_ID = "1p"
SECOND_PROJECTILE_ID = "2p"
THIRD_PROJECTILE_ID = "3p"

PROJECTILE_IDS = [FIRST_PROJECTILE_ID, SECOND_PROJECTILE_ID, THIRD_PROJECTILE_ID]

FIRST_PROJECTILE_DOWN = ""
FIRST_PROJECTILE_UP = ""
FIRST_PROJECTILE_LEFT = ""
FIRST_PROJECTILE_RIGHT = ""

SECOND_PROJECTILE_DOWN = ""
SECOND_PROJECTILE_UP = ""
SECOND_PROJECTILE_LEFT = ""
SECOND_PROJECTILE_RIGHT = ""

THIRD_PROJECTILE_DOWN = ""
THIRD_PROJECTILE_UP = ""
THIRD_PROJECTILE_LEFT = ""
THIRD_PROJECTILE_RIGHT = ""

PROJECTILE_SPRITE_FILES = {
    FIRST_PROJECTILE_ID: [FIRST_PROJECTILE_DOWN, FIRST_PROJECTILE_UP, FIRST_PROJECTILE_LEFT, FIRST_PROJECTILE_RIGHT],
    SECOND_PROJECTILE_ID: [SECOND_PROJECTILE_DOWN, SECOND_PROJECTILE_UP, SECOND_PROJECTILE_LEFT, SECOND_PROJECTILE_RIGHT],
    THIRD_PROJECTILE_ID: [THIRD_PROJECTILE_DOWN, THIRD_PROJECTILE_UP, THIRD_PROJECTILE_LEFT, THIRD_PROJECTILE_RIGHT]
}

PLAYER_SPRITE_HEIGHT = 32
PLAYER_SPRITE_WIDTH = 18
PLAYER_FRAME_COUNT = 5
PLAYER_FRAME_SPACE = 14

PLAYER_ID_SYMB = "!"
ENEMY_ID_SYMB = "#"
PROJECTILE_ID_SYMB = "@"
OBSTACLE_ID_SYMB = "&"

KNIGHT_ID = "!K"
MONK_ID = "!M"
KILLER_ID = "!I"
WIZARD_ID = "!W"
BOXER_ID = "!B"
CAVEMAN_ID = "!C"

PLAYABLE_CHARACTER_IDS = [KNIGHT_ID, MONK_ID, KILLER_ID, WIZARD_ID, CAVEMAN_ID, BOXER_ID]

KNIGHT_DOWN_SPRITES = "assets/knight_sprites/knight_down_sprites.png"
KNIGHT_UP_SPRITES = "assets/knight_sprites/knight_up_sprites.png"
KNIGHT_LEFT_SPRITES = "assets/knight_sprites/knight_left_sprites.png"
KNIGHT_RIGHT_SPRITES = "assets/knight_sprites/knight_right_sprites.png"

WIZARD_DOWN_SPRITES = "assets/wizard_sprites/wizard_down_sprites.png"
WIZARD_UP_SPRITES = "assets/wizard_sprites/wizard_up_sprites.png"
WIZARD_LEFT_SPRITES = "assets/wizard_sprites/wizard_left_sprites.png"
WIZARD_RIGHT_SPRITES = "assets/wizard_sprites/wizard_right_sprites.png"

MONK_DOWN_SPRITES = "assets/monk_sprites/monk_down_sprites.png"
MONK_UP_SPRITES = "assets/monk_sprites/monk_up_sprites.png"
MONK_LEFT_SPRITES = "assets/monk_sprites/monk_left_sprites.png"
MONK_RIGHT_SPRITES = "monk_sprites/monk_right_sprites.png"

BOXER_DOWN_SPRITES = "assets/boxer_sprites/boxer_down_sprites.png"
BOXER_UP_SPRITES = "assets/boxer_sprites/boxer_up_sprites.png"
BOXER_LEFT_SPRITES = "assets/boxer_sprites/boxer_left_sprites.png"
BOXER_RIGHT_SPRITES = "assets/boxer_sprites/boxer_right_sprites.png"

KILLER_DOWN_SPRITES = "assets/killer_sprites/killer_down_sprites.png"
KILLER_UP_SPRITES = "assets/killer_sprites/killer_up_sprites.png"
KILLER_LEFT_SPRITES = "assets/killer_sprites/killer_left_sprites.png"
KILLER_RIGHT_SPRITES = "assets/killer_sprites/killer_right_sprites.png"

CAVEMAN_DOWN_SPRITES = "assets/caveman_sprites/caveman_down_sprites.png"
CAVEMAN_UP_SPRITES = "assets/caveman_sprites/caveman_up_sprites.png"
CAVEMAN_LEFT_SPRITES = "assets/caveman_sprites/caveman_left_sprites.png"
CAVEMAN_RIGHT_SPRITES = "assets/caveman_sprites/caveman_right_sprites.png"

PLAYER_SPRITE_FILES = {
    KNIGHT_ID: [KNIGHT_DOWN_SPRITES, KNIGHT_UP_SPRITES, KNIGHT_LEFT_SPRITES, KNIGHT_RIGHT_SPRITES],
    MONK_ID: [MONK_DOWN_SPRITES, MONK_UP_SPRITES, MONK_LEFT_SPRITES, MONK_RIGHT_SPRITES],
    KILLER_ID: [KILLER_DOWN_SPRITES, KILLER_UP_SPRITES, KILLER_LEFT_SPRITES, KILLER_RIGHT_SPRITES],
    WIZARD_ID: [WIZARD_DOWN_SPRITES, WIZARD_UP_SPRITES, WIZARD_LEFT_SPRITES, WIZARD_RIGHT_SPRITES],
    BOXER_ID: [BOXER_DOWN_SPRITES, BOXER_UP_SPRITES, BOXER_LEFT_SPRITES, BOXER_RIGHT_SPRITES],
    CAVEMAN_ID: [CAVEMAN_DOWN_SPRITES, CAVEMAN_UP_SPRITES, CAVEMAN_LEFT_SPRITES, CAVEMAN_RIGHT_SPRITES]
}

ENEMY_FRAME_SPACE = 0
ENEMY_FRAME_COUNT = 0
ENEMY_WIDTH = 0
ENEMY_HEIGHT = 0

FIRST_ENEMY_ID = "1e"
SECOND_ENEMY_ID = "2e"
THIRD_ENEMY_ID = "3e"

ENEMY_IDS = [FIRST_ENEMY_ID, SECOND_ENEMY_ID, THIRD_ENEMY_ID]

FIRST_ENEMY_DOWN = ""
FIRST_ENEMY_UP = ""
FIRST_ENEMY_LEFT = ""
FIRST_ENEMY_RIGHT = ""

SECOND_ENEMY_DOWN = ""
SECOND_ENEMY_UP = ""
SECOND_ENEMY_LEFT = ""
SECOND_ENEMY_RIGHT = ""

THIRD_ENEMY_DOWN = ""
THIRD_ENEMY_UP = ""
THIRD_ENEMY_LEFT = ""
THIRD_ENEMY_RIGHT = ""

ENEMY_SPRITE_FILES = {
    FIRST_ENEMY_ID: [FIRST_ENEMY_DOWN, FIRST_ENEMY_UP, FIRST_ENEMY_LEFT, FIRST_ENEMY_RIGHT],
    SECOND_ENEMY_ID: [SECOND_ENEMY_DOWN, SECOND_ENEMY_UP, SECOND_ENEMY_LEFT, SECOND_ENEMY_RIGHT],
    THIRD_ENEMY_ID: [THIRD_ENEMY_DOWN, THIRD_ENEMY_UP, THIRD_ENEMY_LEFT, THIRD_ENEMY_RIGHT]
}

OBSTACLE_FRAME_SPACE = 0
OBSTACLE_FRAME_COUNT = 1
OBSTACLE_WIDTH = 0
OBSTACLE_HEIGHT = 0

FIRST_OBSTACLE_ID = "1o"
SECOND_OBSTACLE_ID = "2o"
THIRD_OBSTACLE_ID = "3o"

OBSTACLE_IDS = [FIRST_OBSTACLE_ID, SECOND_OBSTACLE_ID, THIRD_OBSTACLE_ID]

FIRST_OBSTACLE_PATH = ""
SECOND_OBSTACLE_PATH = ""
THIRD_OBSTACLE_PATH = ""

OBSTACLE_IMAGE_FILES = {
    FIRST_OBSTACLE_ID: FIRST_OBSTACLE_PATH,
    SECOND_OBSTACLE_ID: SECOND_OBSTACLE_PATH,
    THIRD_OBSTACLE_ID: THIRD_OBSTACLE_PATH,
}

WEAPON_FRAME_SPACE = 0
WEAPON_FRAME_COUNT = 0
WEAPON_WIDTH = 0
WEAPON_HEIGHT = 0

KNIGHT_WEAPON_ID = "!K_w"
MONK_WEAPON_ID = "!M_w"
KILLER_WEAPON_ID = "!I_w"
WIZARD_WEAPON_ID = "!W_w"
BOXER_WEAPON_ID = "!B_w"
CAVEMAN_WEAPON_ID = "!C_w"

WEAPON_IDS = [
    KNIGHT_WEAPON_ID,
    MONK_WEAPON_ID,
    KILLER_WEAPON_ID,
    WIZARD_WEAPON_ID,
    BOXER_WEAPON_ID,
    CAVEMAN_WEAPON_ID,
]

KNIGHT_WEAPON_LEFT = ""
KNIGHT_WEAPON_RIGHT = ""

MONK_WEAPON_LEFT = ""
MONK_WEAPON_RIGHT = ""

KILLER_WEAPON_LEFT = ""
KILLER_WEAPON_RIGHT = ""

WIZARD_WEAPON_LEFT = ""
WIZARD_WEAPON_RIGHT = ""

BOXER_WEAPON_LEFT = ""
BOXER_WEAPON_RIGHT = ""

CAVEMAN_WEAPON_LEFT = ""
CAVEMAN_WEAPON_RIGHT = ""

WEAPON_SPRITE_FILES = {
    KNIGHT_WEAPON_ID: [KNIGHT_WEAPON_LEFT, KNIGHT_WEAPON_RIGHT],
    MONK_WEAPON_ID: [MONK_WEAPON_LEFT, MONK_WEAPON_RIGHT],
    KILLER_WEAPON_ID: [KILLER_WEAPON_LEFT, KILLER_WEAPON_RIGHT],
    WIZARD_WEAPON_ID: [WIZARD_WEAPON_LEFT, WIZARD_WEAPON_RIGHT],
    BOXER_WEAPON_ID: [BOXER_WEAPON_LEFT, BOXER_WEAPON_RIGHT],
    CAVEMAN_WEAPON_ID: [CAVEMAN_WEAPON_LEFT, CAVEMAN_WEAPON_RIGHT],
}

PLAYER_SCALE = 3
PROJECTILE_SCALE = 3
ENEMY_SCALE = 3
WEAPON_SCALE = 3
OBSTACLE_SCALE = 3
BACKGROUND_SCALE = 1