TOP_LEFT_CORNER = (0,0)

FIRST_BACKGROUND_ID = "1b"
SECOND_BACKGROUND_ID = "2b"
THIRD_BACKGROUND_ID = "3b"
FOURTH_BACKGROUND_ID = "4b"

FIRST_BACKGROUND_PATH = "assets/background_grass.png"
SECOND_BACKGROUND_PATH = ""
THIRD_BACKGROUND_PATH = ""
FOURTH_BACKGROUND_PATH = ""

PROJECTILE_FRAME_SPACE = 0
PROJECTILE_FRAME_COUNT = 0
PROJECTILE_WIDTH = 0
PROJECTILE_HEIGHT = 0


FIRST_PROJECTILE_ID = "1p"
SECOND_PROJECTILE_ID = "2p"
THIRD_PROJECTILE_ID = "3p"

PROJECTILE_IDS = [FIRST_PROJECTILE_ID, SECOND_PROJECTILE_ID, THIRD_BACKGROUND_ID]

FIRST_PROJECTILE_DOWN = ""
FIRST_PROJECTILE_UP = ""
FIRST_PROJECTILE_LEFT = ""
FIRST_PROJECTILE_RIGHT = ""

SECOND_PROJECTILE_DOWN = ""
SECOND_PROJECTILE_UP = ""
SECOND_PROJECTILE_LEFT = ""
SECOND_PROJECTILE_RIGHT = ""

THIRD_PROJECTILE_DOWN = ""
THIRD_PROJECTILE_UP = ""
THIRD_PROJECTILE_LEFT = ""
THIRD_PROJECTILE_RIGHT = ""

PROJECTILE_SPRITE_FILES = {FIRST_PROJECTILE_ID : [FIRST_PROJECTILE_DOWN, FIRST_PROJECTILE_UP, FIRST_PROJECTILE_LEFT, FIRST_PROJECTILE_RIGHT],
                           SECOND_PROJECTILE_ID : [SECOND_PROJECTILE_DOWN, SECOND_PROJECTILE_UP, SECOND_PROJECTILE_LEFT, SECOND_PROJECTILE_RIGHT],
                           THIRD_PROJECTILE_ID : [THIRD_PROJECTILE_DOWN, THIRD_PROJECTILE_UP, THIRD_PROJECTILE_LEFT, THIRD_PROJECTILE_RIGHT]}

PLAYER_SPRITE_HEIGHT = 32
PLAYER_SPRITE_WIDTH = 18
PLAYER_FRAME_COUNT = 5
PLAYER_FRAME_SPACE = 14

PLAYER_ID_SYMB = "!"
ENEMY_ID_SYMB = "#"
PROJECTILE_ID_SYMB = "@"
OBSTACLE_ID_SYMB = "&"

KNIGHT_ID = "!K"
MONK_ID = "!M"
KILLER_ID = "!I"
WIZARD_ID = "!W"
BOXER_ID = "!B"
CAVEMAN_ID = "!C"
PLAYABLE_CHARACTER_IDS = [KNIGHT_ID, MONK_ID, KILLER_ID, WIZARD_ID, CAVEMAN_ID, BOXER_ID]

KNIGHT_DOWN_SPRITES = "knight_sprites/knight_down_sprites.png"
KNIGHT_UP_SPRITES = "knight_sprites/knight_up_sprites.png"
KNIGHT_LEFT_SPRITES = "knight_sprites/knight_left_sprites.png"
KNIGHT_RIGHT_SPRITES = "knight_sprites/knight_right_sprites.png"

WIZARD_DOWN_SPRITES = "wizard_sprites/wizard_down_sprites.png"
WIZARD_UP_SPRITES = "wizard_sprites/wizard_up_sprites.png"
WIZARD_LEFT_SPRITES = "wizard_sprites/wizard_left_sprites.png"
WIZARD_RIGHT_SPRITES = "wizard_sprites/wizard_right_sprites.png"

MONK_DOWN_SPRITES = "monk_sprites/monk_down_sprites.png"
MONK_UP_SPRITES = "monk_sprites/monk_up_sprites.png"
MONK_LEFT_SPRITES = "monk_sprites/monk_left_sprites.png"
MONK_RIGHT_SPRITES = "monk_sprites/monk_right_sprites.png"

BOXER_DOWN_SPRITES = "boxer/boxer_down_sprites.png"
BOXER_UP_SPRITES = "boxer_sprites/boxer_up_sprites.png"
BOXER_LEFT_SPRITES = "boxer_sprites/boxer_left_sprites.png"
BOXER_RIGHT_SPRITES = "boxer_sprites/boxer_right_sprites.png"

KILLER_DOWN_SPRITES = "killer_sprites/killer_down_sprites.png"
KILLER_UP_SPRITES = "killer_sprites/killer_up_sprites.png"
KILLER_LEFT_SPRITES = "killer_sprites/killer_left_sprites.png"
KILLER_RIGHT_SPRITES = "killer_sprites/killer_right_sprites.png"

CAVEMAN_DOWN_SPRITES = "caveman_sprites/caveman_down_sprites.png"
CAVEMAN_UP_SPRITES = "caveman_sprites/caveman_up_sprites.png"
CAVEMAN_LEFT_SPRITES = "caveman_sprites/caveman_left_sprites.png"
CAVEMAN_RIGHT_SPRITES = "caveman_sprites/caveman_right_sprites.png"

PLAYER_SPRITE_FILES = {KNIGHT_ID : [KNIGHT_DOWN_SPRITES, KNIGHT_UP_SPRITES, KNIGHT_LEFT_SPRITES, KNIGHT_RIGHT_SPRITES],
                MONK_ID : [MONK_DOWN_SPRITES, MONK_UP_SPRITES, WIZARD_LEFT_SPRITES, MONK_RIGHT_SPRITES],
                KILLER_ID : [KILLER_DOWN_SPRITES, KILLER_UP_SPRITES, KILLER_LEFT_SPRITES, KILLER_RIGHT_SPRITES],
                WIZARD_ID : [WIZARD_DOWN_SPRITES, WIZARD_UP_SPRITES, WIZARD_LEFT_SPRITES, WIZARD_RIGHT_SPRITES],
                BOXER_ID : [BOXER_DOWN_SPRITES, BOXER_UP_SPRITES, BOXER_LEFT_SPRITES, BOXER_RIGHT_SPRITES],
                CAVEMAN_ID : [CAVEMAN_DOWN_SPRITES, CAVEMAN_UP_SPRITES, CAVEMAN_LEFT_SPRITES, CAVEMAN_RIGHT_SPRITES]}